In [10]:
import numpy as np
import pandas as pd

<h2>defining the dataset<h2>

In [12]:
breast = pd.read_csv("data.csv")
breast.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [13]:
breast['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

<h2>Cleaning the Data<h2>

In [15]:
breast.shape

(569, 33)

In [16]:
breast.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [17]:
breast.duplicated().sum()

0

In [18]:
breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [19]:
breast.drop("Unnamed: 32", axis=1, inplace=True)

In [20]:
breast.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

**for this project we use level encoding because the output is categorical**

<h2>encoding the target variable<h2>

**Replaces the character values into 0 and 1 coz machine understands the binary lang "m":1 if cancer presents malignant "b":0 if the cancer did not presednt benign**

In [24]:
breast['diagnosis'] = breast['diagnosis'].map({"M": 1, "B": 0})

In [25]:
breast['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

**spliting the data into training and testing**

In [27]:
# 1. Features and target
X = breast.drop('diagnosis', axis=1)
y = breast['diagnosis']

# 2. Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42
)

**Scaling the feature to better performance of model**

In [29]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [30]:
X_train

array([[-0.23841709,  0.35581987, -1.72664707, ...,  1.05652305,
         0.51844283,  0.98925483],
       [-0.23209947, -0.37326674,  0.50881308, ..., -0.89667412,
        -0.63236707, -0.11469617],
       [-0.23246672,  1.4033581 , -0.15144941, ...,  1.46353548,
         1.02587412, -0.03369823],
       ...,
       [-0.17027269,  0.02898794, -0.56411347, ..., -1.2463348 ,
        -0.67979055, -1.26509354],
       [-0.23207399, -0.05760855,  0.09614902, ...,  1.05652305,
         0.45995387,  1.24414347],
       [-0.23242557, -0.5604269 ,  0.30837625, ..., -0.6145405 ,
        -0.30672581, -0.8357478 ]])

In [31]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [32]:
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)

In [33]:
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0], dtype=int64)

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9787234042553191

<h2>Prediction System<h2>

In [36]:
input_text=(-0.23250538,  0.82511699, -0.66315284,  0.96181678,  0.68936555,
        1.63561451,  2.39991193,  1.6966724 ,  2.38986091,  4.55838605,
        1.57967131,  2.17560637, -0.44389265,  2.04714969,  1.41945307,
        0.30152063,  0.69125126,  0.15943153,  1.89652406,  0.31709006,
        1.35315121,  1.22293769, -0.68774672,  1.33901374,  0.99404377,
        0.98161345,  0.96612202,  0.57891167,  2.1711821 ,  1.86210823,
        1.26680023)
np_df=np.asarray(input_text)
prediction = lg.predict(np_df.reshape(1,-1))

if prediction[0] == 1:
    print("Cancerous")
else:
    print("not Cancerous")

Cancerous

**taking the below values and put it into input to know whether the input is cancerous or not**

In [38]:
X_train[10]

array([-0.23250538,  0.82511699, -0.66315284,  0.96181678,  0.68936555,
        1.63561451,  2.39991193,  1.6966724 ,  2.38986091,  4.55838605,
        1.57967131,  2.17560637, -0.44389265,  2.04714969,  1.41945307,
        0.30152063,  0.69125126,  0.15943153,  1.89652406,  0.31709006,
        1.35315121,  1.22293769, -0.68774672,  1.33901374,  0.99404377,
        0.98161345,  0.96612202,  0.57891167,  2.1711821 ,  1.86210823,
        1.26680023])

In [71]:
import pickle
pickle.dump(lg,open("model.pkl",'wb'))
print("Model expects", lg.n_features_in_, "features")

Model expects 31 features

In [53]:
breast.tail()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
564,926424,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [96]:
malignant_df = breast[breast['diagnosis'] == 1]

# Show the first malignant sample
print(malignant_df.head(1))

       id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  842302          1        17.99         10.38           122.8     1001.0

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33            184.6      2019.0

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654

   symmetry_worst  fractal_dimension_worst
0          0.4601                   0.1189

[1 rows x 32 columns]

In [98]:
malignant_sample = malignant_df.iloc[0].tolist()
print(malignant_sample)

[842302.0, 1.0, 17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019.0, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]

In [100]:
X_train[10]

array([-0.23250538,  0.82511699, -0.66315284,  0.96181678,  0.68936555,
        1.63561451,  2.39991193,  1.6966724 ,  2.38986091,  4.55838605,
        1.57967131,  2.17560637, -0.44389265,  2.04714969,  1.41945307,
        0.30152063,  0.69125126,  0.15943153,  1.89652406,  0.31709006,
        1.35315121,  1.22293769, -0.68774672,  1.33901374,  0.99404377,
        0.98161345,  0.96612202,  0.57891167,  2.1711821 ,  1.86210823,
        1.26680023])